name: Create Release
on:
  push:
    tags:
      - '*'
jobs:
  create-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Build Changelog
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ github.token }}

      - name: Get the version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ github.token }}
          tag_name: ${{ github.ref }}
          name: ${{ steps.version.outputs.VERSION }}
          body: ${{steps.changelog.outputs.changelog}}
